/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1_so;

import javax.swing.JLabel;

/**
 *
 * @author daniela
 */
public class Cartoon extends javax.swing.JFrame {

    /**
     * Creates new form Cartoon
     */
    public Cartoon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel24 = new javax.swing.JLabel();
        DriveGuiones = new javax.swing.JLabel();
        DriveEscensarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        DriveAnimaciones = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DriveDoblajes = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        DrivePlot = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        deadline = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        capitulos = new javax.swing.JLabel();
        capitulosPT = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        diastrans = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        UtilidadCartoon = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        EgresosCartoon = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        IngresosCartoon = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        PMestado = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        PMfaltas = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        $faltasPM = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        DirEstado = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel24.setText("PERSONAL DIRECTIVO");

        DriveGuiones.setText("0");

        DriveEscensarios.setText("0");

        jLabel1.setText("CARTOON NETWORK");

        DriveAnimaciones.setText("0");

        jLabel2.setText("ACTIVIDADES");

        DriveDoblajes.setText("0");

        jLabel3.setText("Director:");

        DrivePlot.setText("0");

        jLabel4.setText("Project Manager:");

        jLabel5.setText("Faltas PM:");

        jLabel21.setText("LISTOS");

        jLabel6.setText("TIEMPO");

        jLabel22.setText("Capítulos estándar:");

        jLabel7.setText("Días transcurridos:");

        jLabel23.setText("Capítulos con PlotTwist:");

        jLabel8.setText("Próximo deadline:");

        deadline.setText("0");

        jLabel9.setText("FINANZAS");

        jLabel10.setText("Ingresos:");

        capitulos.setText("0");

        capitulosPT.setText("0");

        jLabel11.setText("Egresos:");

        diastrans.setText("0");

        jLabel12.setText("Utilidad:");

        UtilidadCartoon.setText("0");

        jLabel13.setText("PRODUCCIÓN");

        EgresosCartoon.setText("0");

        jLabel14.setText("Partes");

        IngresosCartoon.setText("0");

        jLabel15.setText("Guiones");

        PMestado.setText("-");

        jLabel16.setText("Escenarios");

        PMfaltas.setText("0");

        jLabel17.setText("Animaciones");

        $faltasPM.setText("$");

        jLabel18.setText("Doblajes");

        DirEstado.setText("0");

        jLabel19.setText("PlotTwists");

        jLabel20.setText("Drive");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addGap(359, 359, 359))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(DirEstado))
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IngresosCartoon))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(EgresosCartoon))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(diastrans))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent($faltasPM, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PMfaltas, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(PMestado, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(UtilidadCartoon)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel15)
                                        .addComponent(jLabel17)
                                        .addComponent(jLabel19))
                                    .addGap(58, 58, 58)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(DriveEscensarios)
                                        .addComponent(DriveGuiones)
                                        .addComponent(DriveAnimaciones)
                                        .addComponent(DriveDoblajes)
                                        .addComponent(DrivePlot)))
                                .addComponent(jLabel21)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel22)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(capitulos))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(18, 18, 18)
                                    .addComponent(capitulosPT))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(69, 69, 69)
                                    .addComponent(jLabel20)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(46, 46, 46)))
                        .addGap(74, 74, 74))))
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(DriveGuiones))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(DriveEscensarios))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(DriveAnimaciones))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(DriveDoblajes))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(DrivePlot))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(capitulos))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(capitulosPT)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel20))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DirEstado))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PMestado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PMfaltas)
                            .addComponent($faltasPM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(diastrans))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(deadline))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(IngresosCartoon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(EgresosCartoon))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(UtilidadCartoon))))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartoon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartoon().setVisible(true);
            }
        });
    }

    public JLabel get$faltasPM() {
        return $faltasPM;
    }

    public void set$faltasPM(JLabel $faltasPM) {
        this.$faltasPM = $faltasPM;
    }

    public JLabel getDirEstado() {
        return DirEstado;
    }

    public void setDirEstado(JLabel DirEstado) {
        this.DirEstado = DirEstado;
    }

    public JLabel getDriveAnimaciones() {
        return DriveAnimaciones;
    }

    public void setDriveAnimaciones(JLabel DriveAnimaciones) {
        this.DriveAnimaciones = DriveAnimaciones;
    }

    public JLabel getDriveDoblajes() {
        return DriveDoblajes;
    }

    public void setDriveDoblajes(JLabel DriveDoblajes) {
        this.DriveDoblajes = DriveDoblajes;
    }

    public JLabel getDriveEscensarios() {
        return DriveEscensarios;
    }

    public void setDriveEscensarios(JLabel DriveEscensarios) {
        this.DriveEscensarios = DriveEscensarios;
    }

    public JLabel getDriveGuiones() {
        return DriveGuiones;
    }

    public void setDriveGuiones(JLabel DriveGuiones) {
        this.DriveGuiones = DriveGuiones;
    }

    public JLabel getDrivePlot() {
        return DrivePlot;
    }

    public void setDrivePlot(JLabel DrivePlot) {
        this.DrivePlot = DrivePlot;
    }

    public JLabel getEgresosCartoon() {
        return EgresosCartoon;
    }

    public void setEgresosCartoon(JLabel EgresosCartoon) {
        this.EgresosCartoon = EgresosCartoon;
    }

    public JLabel getIngresosCartoon() {
        return IngresosCartoon;
    }

    public void setIngresosCartoon(JLabel IngresosCartoon) {
        this.IngresosCartoon = IngresosCartoon;
    }

    public JLabel getPMestado() {
        return PMestado;
    }

    public void setPMestado(JLabel PMestado) {
        this.PMestado = PMestado;
    }

    public JLabel getPMfaltas() {
        return PMfaltas;
    }

    public void setPMfaltas(JLabel PMfaltas) {
        this.PMfaltas = PMfaltas;
    }

    public JLabel getUtilidadCartoon() {
        return UtilidadCartoon;
    }

    public void setUtilidadCartoon(JLabel UtilidadCartoon) {
        this.UtilidadCartoon = UtilidadCartoon;
    }

    public JLabel getCapitulos() {
        return capitulos;
    }

    public void setCapitulos(JLabel capitulos) {
        this.capitulos = capitulos;
    }

    public JLabel getCapitulosPT() {
        return capitulosPT;
    }

    public void setCapitulosPT(JLabel capitulosPT) {
        this.capitulosPT = capitulosPT;
    }

    public JLabel getDeadline() {
        return deadline;
    }

    public void setDeadline(JLabel deadline) {
        this.deadline = deadline;
    }

    public JLabel getDiastrans() {
        return diastrans;
    }

    public void setDiastrans(JLabel diastrans) {
        this.diastrans = diastrans;
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $faltasPM;
    private javax.swing.JLabel DirEstado;
    private javax.swing.JLabel DriveAnimaciones;
    private javax.swing.JLabel DriveDoblajes;
    private javax.swing.JLabel DriveEscensarios;
    private javax.swing.JLabel DriveGuiones;
    private javax.swing.JLabel DrivePlot;
    private javax.swing.JLabel EgresosCartoon;
    private javax.swing.JLabel IngresosCartoon;
    private javax.swing.JLabel PMestado;
    private javax.swing.JLabel PMfaltas;
    private javax.swing.JLabel UtilidadCartoon;
    private javax.swing.JLabel capitulos;
    private javax.swing.JLabel capitulosPT;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel diastrans;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
