/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1_so;

import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gabriellavetencourt
 */
public class Main extends javax.swing.JFrame {

        Empresa Nickelodeon = new Empresa(19, "Nickelodeon");
        Nickelodeon nick = new Nickelodeon();
        
        int duracionDia;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        
         //Se pasan los labels correspondientes a cada compañia y sus drives para manipular la interfaz        
        
        
        JLabel[] NickDriveLabels = {nick.getDriveGuiones(), nick.getDriveEscensarios(), nick.getDriveAnimaciones(), nick.getDriveDoblajes(), nick.getDrivePlot(), nick.getDeadline(), nick.getCapitulos(), nick.getCapitulosPT(), nick.getDiastrans()};
        JLabel[] NickLabels = {TrabajadoresNick, GuionistasNick, DisenadoresNick, AnimadorNick, ActoresNick, GuioPlotNick, EnsambladoresNick, nick.getIngresosNick(), nick.getUtilidadNick(), nick.getEgresosNick()};
//        DevQty2, NarrativeQty2, LevelQty2, SpriteQty2, LogicQty2, DLCQty2, IntegratorQty2,
        
//        JLabel[] StarChannelDriveLabels = {narrativeqtyGUI1, levelqtyGUI1, spriteqtyGUI1, logicqtyGUI2, dlcqtyGUI1, DeadlineGUI1, readygamesqtyGUI1, readydlcGUI1, dayspassedGUI2};  
//        JLabel[] StarChannelLabels = {DevQty1, NarrativeQty1, LevelQty1, SpriteQty1, LogicQty1, DLCQty1, IntegratorQty1, DevQty3, NarrativeQty3, LevelQty3, SpriteQty3, LogicQty3, DLCQty3, IntegratorQty3, incomeGUI1, utilityGUI2, totalsalariesGUI1};
//        
//        JLabel[] CartoonDriveLabels = {narrativeqtyGUI1, levelqtyGUI1, spriteqtyGUI1, logicqtyGUI2, dlcqtyGUI1, DeadlineGUI1, readygamesqtyGUI1, readydlcGUI1, dayspassedGUI2};  
//        JLabel[] CartoonLabels = {DevQty1, NarrativeQty1, LevelQty1, SpriteQty1, LogicQty1, DLCQty1, IntegratorQty1, DevQty3, NarrativeQty3, LevelQty3, SpriteQty3, LogicQty3, DLCQty3, IntegratorQty3, incomeGUI1, utilityGUI2, totalsalariesGUI1};
//        
        this.Nickelodeon.getDrive().setLabels(NickDriveLabels);
        this.Nickelodeon.setLabels(NickLabels);
//        this.Nickelodeon.getCompanyDrive().setLabels(NickDriveLabels);
        

//        
//        this.squareEnix.getCompanyDrive().setLabels(CartoonDriveLabels);
//        this.squareEnix.setLabels(CartoonLabels);
        this.DuracionDia.setText(Integer.toString(duracionDia));
        
       
    //Lectura de la configuracion guardada en txt 
//        readConfig();
        
    //Se refleja la lectura la lectura de desarrolladores maximos de cada compañia    
        TrabajadoresNick.setText(Integer.toString(this.Nickelodeon.getCantTrabajadores()));
//        maxDevsGUI1.setText(Integer.toString(this.squareEnix.getMaxDevs()));
        
    //Conversion de hora y minutos   
        int duracionHora = duracionDia/24;
        int duracionMin = duracionHora/60;
        if(duracionHora == 0){
            duracionHora = 1;
        }
        if(duracionMin == 0){
            duracionMin = 1;
        }
 

    //Se crea e inicializan los directores y pms de cada compañia
        ProjectManager nickPM = new ProjectManager( this.duracionDia, duracionHora, duracionMin,this.Nickelodeon.getDrive(),this.Nickelodeon.getMutex(), nick.getPMestado());
        Director Nickdir = new Director(this.Nickelodeon.getDrive(), this.Nickelodeon.getMutex(), nickPM, duracionMin, nick.getPMfaltas());
        RevisionPM NickRevPM = new RevisionPM( this.duracionDia, duracionHora, duracionMin, Nickdir, nick.getDirEstado(), this.Nickelodeon);

        
//        ProjectManager squareMan = new ProjectManager(this.dayDuration, duracionHora, duracionMin, this.squareEnix.getCompanyDrive(), this.squareEnix.getMutex(), PMstateGUI1);
//        Director squareDir = new Director(this.squareEnix.getCompanyDrive(), this.squareEnix.getMutex(), squareMan, duracionMin, PMfaultsGUI1, PMfaults$GUI1);
//        RevisionPM squareWatch = new RevisionPM(this.dayDuration, duracionHora, duracionMin, squareDir, directorstateGUI1,this.squareEnix);
//        
//        
        nickPM.start();
        Nickdir.start();
        NickRevPM.start();
        
//        squareMan.start();
//        squareDir.start();
//        squareWatch.start();
//   

    
    }
    
    public void MaxErrorTrab(){
        JOptionPane.showMessageDialog(null, "Máximo de trabajadores alcanzado, disminuya la cantidad!");
    }
     
    public void minErrorTrab(){
        JOptionPane.showMessageDialog(null, "No es posible disminuir la cantidad de trabajadores.");
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TrabajadoresNick = new javax.swing.JLabel();
        GuionistasNick = new javax.swing.JLabel();
        DisenadoresNick = new javax.swing.JLabel();
        AnimadorNick = new javax.swing.JLabel();
        ActoresNick = new javax.swing.JLabel();
        GuioPlotNick = new javax.swing.JLabel();
        EnsambladoresNick = new javax.swing.JLabel();
        MenosGuionistasNick = new javax.swing.JButton();
        MenosDisenadorNick = new javax.swing.JButton();
        MenosAnimadorNick = new javax.swing.JButton();
        MenosActoresNick = new javax.swing.JButton();
        MenosGuioPlotNick = new javax.swing.JButton();
        MenosEnsambladoresNick = new javax.swing.JButton();
        MasGuionistaNick = new javax.swing.JButton();
        MasAnimadorNick = new javax.swing.JButton();
        MasDisenadorNick = new javax.swing.JButton();
        MasActorNick = new javax.swing.JButton();
        MasGuioPlotNick = new javax.swing.JButton();
        MasEnsambladoresNick = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        DuracionDia = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        salir = new javax.swing.JButton();
        masDeadline = new javax.swing.JButton();
        deadline = new javax.swing.JLabel();
        menosDeadline = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nickelodeon");

        jLabel2.setText("Trabajadores disponibles:");

        jLabel3.setText("Guionistas");

        jLabel4.setText("Diseñador de escenarios");

        jLabel5.setText("Animador de personajes");

        jLabel6.setText("Actores doblaje");

        jLabel7.setText("Guionista de Plotwist");

        jLabel8.setText("Ensambladores");

        TrabajadoresNick.setText("1");

        GuionistasNick.setText("0");

        DisenadoresNick.setText("0");

        AnimadorNick.setText("0");

        ActoresNick.setText("0");

        GuioPlotNick.setText("0");

        EnsambladoresNick.setText("0");

        MenosGuionistasNick.setText("-");
        MenosGuionistasNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosGuionistasNickActionPerformed(evt);
            }
        });

        MenosDisenadorNick.setText("-");
        MenosDisenadorNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosDisenadorNickActionPerformed(evt);
            }
        });

        MenosAnimadorNick.setText("-");
        MenosAnimadorNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosAnimadorNickActionPerformed(evt);
            }
        });

        MenosActoresNick.setText("-");
        MenosActoresNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosActoresNickActionPerformed(evt);
            }
        });

        MenosGuioPlotNick.setText("-");
        MenosGuioPlotNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosGuioPlotNickActionPerformed(evt);
            }
        });

        MenosEnsambladoresNick.setText("-");
        MenosEnsambladoresNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenosEnsambladoresNickActionPerformed(evt);
            }
        });

        MasGuionistaNick.setText("+");
        MasGuionistaNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasGuionistaNickActionPerformed(evt);
            }
        });

        MasAnimadorNick.setText("+");
        MasAnimadorNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasAnimadorNickActionPerformed(evt);
            }
        });

        MasDisenadorNick.setText("+");
        MasDisenadorNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasDisenadorNickActionPerformed(evt);
            }
        });

        MasActorNick.setText("+");
        MasActorNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasActorNickActionPerformed(evt);
            }
        });

        MasGuioPlotNick.setText("+");
        MasGuioPlotNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasGuioPlotNickActionPerformed(evt);
            }
        });

        MasEnsambladoresNick.setText("+");
        MasEnsambladoresNick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MasEnsambladoresNickActionPerformed(evt);
            }
        });

        jLabel9.setText("TIEMPO");

        jLabel10.setText("Duracion de un día:");

        jLabel11.setText("segundos");

        jLabel12.setText("Deadline de entrega:");

        jLabel13.setText("días");

        jTabbedPane1.addTab("Inicio", jTabbedPane2);
        jTabbedPane1.addTab("Nickelodeon", jTabbedPane3);

        salir.setText("Salir");
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });

        masDeadline.setText("+");
        masDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                masDeadlineActionPerformed(evt);
            }
        });

        deadline.setText("0");

        menosDeadline.setText("-");
        menosDeadline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosDeadlineActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GuioPlotNick)
                                .addGap(18, 18, 18)
                                .addComponent(MenosGuioPlotNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasGuioPlotNick))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ActoresNick)
                                .addGap(18, 18, 18)
                                .addComponent(MenosActoresNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasActorNick))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AnimadorNick)
                                .addGap(18, 18, 18)
                                .addComponent(MenosAnimadorNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasAnimadorNick))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(DisenadoresNick)
                                .addGap(18, 18, 18)
                                .addComponent(MenosDisenadorNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasDisenadorNick))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(GuionistasNick)
                                .addGap(18, 18, 18)
                                .addComponent(MenosGuionistasNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasGuionistaNick))
                            .addComponent(TrabajadoresNick)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(EnsambladoresNick)
                                .addGap(18, 18, 18)
                                .addComponent(MenosEnsambladoresNick)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MasEnsambladoresNick))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 213, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(108, 108, 108)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(DuracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(menosDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(masDeadline)))))
                        .addGap(306, 306, 306))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(salir)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(TrabajadoresNick))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(GuionistasNick)
                    .addComponent(MenosGuionistasNick)
                    .addComponent(MasGuionistaNick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(DisenadoresNick)
                    .addComponent(MenosDisenadorNick)
                    .addComponent(MasDisenadorNick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(AnimadorNick)
                    .addComponent(MenosAnimadorNick)
                    .addComponent(MasAnimadorNick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ActoresNick)
                    .addComponent(MenosActoresNick)
                    .addComponent(MasActorNick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(GuioPlotNick)
                    .addComponent(MenosGuioPlotNick)
                    .addComponent(MasGuioPlotNick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(EnsambladoresNick)
                    .addComponent(MenosEnsambladoresNick)
                    .addComponent(MasEnsambladoresNick))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(DuracionDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(masDeadline)
                    .addComponent(deadline)
                    .addComponent(jLabel13)
                    .addComponent(menosDeadline))
                .addGap(2, 2, 2)
                .addComponent(salir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenosGuionistasNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosGuionistasNickActionPerformed
        // TODO add your handling code here:
        if(this.Nickelodeon.getGuionistas().getSize() > 1){
            this.Nickelodeon.eliminarTrabajador(1);
        }else{
            minErrorTrab();
        }  
    }//GEN-LAST:event_MenosGuionistasNickActionPerformed

    private void MenosDisenadorNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosDisenadorNickActionPerformed
        // TODO add your handling code here:
        if(this.Nickelodeon.getDisenadores().getSize() > 1){
            this.Nickelodeon.eliminarTrabajador(1);
        }else{
            minErrorTrab();
        }   
    }//GEN-LAST:event_MenosDisenadorNickActionPerformed

    private void MenosAnimadorNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosAnimadorNickActionPerformed
        // TODO add your handling code here:
         if(this.Nickelodeon.getAnimadores().getSize() > 1){
            this.Nickelodeon.eliminarTrabajador(1);
        }else{
            minErrorTrab();
        }
    }//GEN-LAST:event_MenosAnimadorNickActionPerformed

    private void MenosActoresNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosActoresNickActionPerformed
        // TODO add your handling code here:
         if(this.Nickelodeon.getActores().getSize() > 1){
            this.Nickelodeon.eliminarTrabajador(1);
        }else{
            minErrorTrab();
        }
    }//GEN-LAST:event_MenosActoresNickActionPerformed

    private void MenosGuioPlotNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosGuioPlotNickActionPerformed
        // TODO add your handling code here:
         if(this.Nickelodeon.getGuionistasPT().getSize() > 1){
            this.Nickelodeon.eliminarTrabajador(1);
        }else{
            minErrorTrab();
        }
    }//GEN-LAST:event_MenosGuioPlotNickActionPerformed

    private void MenosEnsambladoresNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenosEnsambladoresNickActionPerformed
        // TODO add your handling code here:
         if(this.Nickelodeon.getEnsambladores().getSize() > 1){
            this.Nickelodeon.eliminarTrabajador(1);
        }else{
            minErrorTrab();
        }
    }//GEN-LAST:event_MenosEnsambladoresNickActionPerformed

    private void MasGuionistaNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasGuionistaNickActionPerformed
        // TODO add your handling code here:
       Trabajadores nickt1 = new Trabajadores(0, "Nickelodeon", duracionDia, Nickelodeon.getDrive(), Nickelodeon.getMutex());
        Nickelodeon.AggTrabajador(nickt1);
    }//GEN-LAST:event_MasGuionistaNickActionPerformed

    private void MasAnimadorNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasAnimadorNickActionPerformed
        // TODO add your handling code here:
        Trabajadores nickt1 = new Trabajadores(2, "Nickelodeon", duracionDia, Nickelodeon.getDrive(), Nickelodeon.getMutex());
        Nickelodeon.AggTrabajador(nickt1);
         
    }//GEN-LAST:event_MasAnimadorNickActionPerformed

    private void MasDisenadorNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasDisenadorNickActionPerformed
        // TODO add your handling code here:
        Trabajadores nickt1 = new Trabajadores(1, "Nickelodeon", duracionDia, Nickelodeon.getDrive(), Nickelodeon.getMutex());
        Nickelodeon.AggTrabajador(nickt1);                         
    }//GEN-LAST:event_MasDisenadorNickActionPerformed

    private void MasActorNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasActorNickActionPerformed
        // TODO add your handling code here:
        Trabajadores nickt1 = new Trabajadores(3, "Nickelodeon", duracionDia, Nickelodeon.getDrive(), Nickelodeon.getMutex());
        Nickelodeon.AggTrabajador(nickt1);
    }//GEN-LAST:event_MasActorNickActionPerformed

    private void MasGuioPlotNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasGuioPlotNickActionPerformed
        // TODO add your handling code here:
        Trabajadores nickt1 = new Trabajadores(4, "Nickelodeon", duracionDia, Nickelodeon.getDrive(), Nickelodeon.getMutex());
        Nickelodeon.AggTrabajador(nickt1);
    }//GEN-LAST:event_MasGuioPlotNickActionPerformed

    private void MasEnsambladoresNickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MasEnsambladoresNickActionPerformed
        // TODO add your handling code here:
        Ensamblador nicke1 = new Ensamblador( Nickelodeon.getDrive(), Nickelodeon.getMutex(), duracionDia);
        Nickelodeon.AggEnsamblador(nicke1);
    }//GEN-LAST:event_MasEnsambladoresNickActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    private void menosDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosDeadlineActionPerformed
        // TODO add your handling code here:
        int deadlineActual = Nickelodeon.getDrive().getDeadline();
        if (deadlineActual > 1) {
            deadlineActual--;
            Nickelodeon.getDrive().setDeadline(deadlineActual);
//            squareEnix.getCompanyDrive().setDeadLine(deadlineActual);
                    this.deadline.setText(Integer.toString(deadlineActual));

        }
    }//GEN-LAST:event_menosDeadlineActionPerformed

    private void masDeadlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_masDeadlineActionPerformed
        // TODO add your handling code here:
        int deadlineActual = Nickelodeon.getDrive().getDeadline(); 
        deadlineActual++;
        Nickelodeon.getDrive().setDeadline(deadlineActual);
//        squareEnix.getCompanyDrive().setDeadLine(deadlineActual);
        
        this.deadline.setText(Integer.toString(deadlineActual));
    }//GEN-LAST:event_masDeadlineActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActoresNick;
    private javax.swing.JLabel AnimadorNick;
    private javax.swing.JLabel DisenadoresNick;
    private javax.swing.JTextField DuracionDia;
    private javax.swing.JLabel EnsambladoresNick;
    private javax.swing.JLabel GuioPlotNick;
    private javax.swing.JLabel GuionistasNick;
    private javax.swing.JButton MasActorNick;
    private javax.swing.JButton MasAnimadorNick;
    private javax.swing.JButton MasDisenadorNick;
    private javax.swing.JButton MasEnsambladoresNick;
    private javax.swing.JButton MasGuioPlotNick;
    private javax.swing.JButton MasGuionistaNick;
    private javax.swing.JButton MenosActoresNick;
    private javax.swing.JButton MenosAnimadorNick;
    private javax.swing.JButton MenosDisenadorNick;
    private javax.swing.JButton MenosEnsambladoresNick;
    private javax.swing.JButton MenosGuioPlotNick;
    private javax.swing.JButton MenosGuionistasNick;
    private javax.swing.JLabel TrabajadoresNick;
    private javax.swing.JLabel deadline;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JButton masDeadline;
    private javax.swing.JButton menosDeadline;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
