/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package p1_so;

import javax.swing.JLabel;

/**
 *
 * @author gabriellavetencourt
 */
public class Nickelodeon extends javax.swing.JFrame {

    /**
     * Creates new form Nickelodeon
     */
    public Nickelodeon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        DriveGuiones1 = new javax.swing.JLabel();
        DriveEscensarios1 = new javax.swing.JLabel();
        DriveAnimaciones1 = new javax.swing.JLabel();
        DriveDoblajes1 = new javax.swing.JLabel();
        DrivePlot1 = new javax.swing.JLabel();
        DriveGuiones6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        deadline1 = new javax.swing.JLabel();
        capitulos1 = new javax.swing.JLabel();
        capitulosPT1 = new javax.swing.JLabel();
        diastrans1 = new javax.swing.JLabel();
        UtilidadNick1 = new javax.swing.JLabel();
        EgresosNick1 = new javax.swing.JLabel();
        IngresosNick1 = new javax.swing.JLabel();
        PMestado1 = new javax.swing.JLabel();
        PMfaltas1 = new javax.swing.JLabel();
        $faltasPM = new javax.swing.JLabel();
        DirEstado1 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("NICKELODEON");

        jLabel2.setText("ACTIVIDADES");

        jLabel3.setText("Director:");

        jLabel4.setText("Project Manager:");

        jLabel5.setText("Faltas PM:");

        jLabel6.setText("TIEMPO");

        jLabel7.setText("Días transcurridos:");

        jLabel8.setText("Próximo deadline:");

        jLabel9.setText("FINANZAS");

        jLabel10.setText("Ingresos:");

        jLabel11.setText("Egresos:");

        jLabel12.setText("Utilidad:");

        jLabel13.setText("PRODUCCIÓN");

        jLabel14.setText("Partes");

        jLabel15.setText("Guiones");

        jLabel16.setText("Escenarios");

        jLabel17.setText("Animaciones");

        jLabel18.setText("Doblajes");

        jLabel19.setText("PlotTwists");

        jLabel20.setText("Drive");

        DriveGuiones1.setText("0");

        DriveEscensarios1.setText("0");

        DriveAnimaciones1.setText("0");

        DriveDoblajes1.setText("0");

        DrivePlot1.setText("0");

        jLabel21.setText("LISTOS");

        jLabel22.setText("Capítulos estándar:");

        jLabel23.setText("Capítulos con PlotTwist:");

        deadline1.setText("0");

        capitulos1.setText("0");

        capitulosPT1.setText("0");

        diastrans1.setText("0");

        UtilidadNick1.setText("0");

        EgresosNick1.setText("0");

        IngresosNick1.setText("0");

        PMestado1.setText("-");

        PMfaltas1.setText("0");

        $faltasPM.setText("$");

        DirEstado1.setText("0");

        jLabel24.setText("PERSONAL DIRECTIVO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(DirEstado1))
                            .addComponent(jLabel6)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IngresosNick1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EgresosNick1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(deadline1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(diastrans1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent($faltasPM, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PMfaltas1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(PMestado1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UtilidadNick1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel19))
                                .addGap(58, 58, 58)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(DriveEscensarios1)
                                    .addComponent(DriveGuiones1)
                                    .addComponent(DriveAnimaciones1)
                                    .addComponent(DriveDoblajes1)
                                    .addComponent(DrivePlot1)))
                            .addComponent(jLabel21)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(capitulos1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(capitulosPT1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(69, 69, 69)
                                .addComponent(jLabel20)))
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(139, 139, 139))))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel24)
                .addContainerGap(331, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(193, 193, 193))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(415, Short.MAX_VALUE)
                    .addComponent(DriveGuiones6)
                    .addGap(77, 77, 77)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel13))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel15)
                                    .addComponent(DriveGuiones1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(DriveEscensarios1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(DriveAnimaciones1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel18)
                                    .addComponent(DriveDoblajes1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(DrivePlot1))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel21)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(capitulos1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel23)
                                    .addComponent(capitulosPT1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel20))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel24)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(DirEstado1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(PMestado1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(PMfaltas1)
                            .addComponent($faltasPM))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(diastrans1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(deadline1))
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(IngresosNick1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(EgresosNick1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(UtilidadNick1))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(162, 162, 162)
                    .addComponent(DriveGuiones6)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Nickelodeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Nickelodeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Nickelodeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Nickelodeon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Nickelodeon().setVisible(true);
            }
        });
    }

    public JLabel getDirEstado() {
        return DirEstado1;
    }

    public void setDirEstado(JLabel DirEstado) {
        this.DirEstado1 = DirEstado;
    }

    public JLabel getPMfaltas() {
        return PMfaltas1;
    }

    public void setPMfaltas(JLabel PMfaltas) {
        this.PMfaltas1 = PMfaltas;
    }

    public JLabel getPMestado() {
        return PMestado1;
    }

    public void setPMestado(JLabel PMestado) {
        this.PMestado1 = PMestado;
    }

    public JLabel getEgresosNick() {
        return EgresosNick1;
    }

    public void setEgresosNick(JLabel EgresosNick) {
        this.EgresosNick1 = EgresosNick;
    }

    public JLabel getIngresosNick() {
        return IngresosNick1;
    }

    public void setIngresosNick(JLabel IngresosNick) {
        this.IngresosNick1 = IngresosNick;
    }

    public JLabel getUtilidadNick() {
        return UtilidadNick1;
    }

    public void setUtilidadNick(JLabel UtilidadNick) {
        this.UtilidadNick1 = UtilidadNick;
    }

    public JLabel getDiastrans() {
        return diastrans1;
    }

    public void setDiastrans(JLabel diastrans) {
        this.diastrans1 = diastrans;
    }

    public JLabel getCapitulos() {
        return capitulos1;
    }

    public void setCapitulos(JLabel capitulos) {
        this.capitulos1 = capitulos;
    }

    public JLabel getCapitulosPT() {
        return capitulosPT1;
    }

    public void setCapitulosPT(JLabel capitulosPT) {
        this.capitulosPT1 = capitulosPT;
    }

    public JLabel getDeadline() {
        return deadline1;
    }

    public void setDeadline(JLabel deadline) {
        this.deadline1 = deadline;
    }

    public JLabel getDriveAnimaciones() {
        return DriveAnimaciones1;
    }

    public void setDriveAnimaciones(JLabel DriveAnimaciones) {
        this.DriveAnimaciones1 = DriveAnimaciones;
    }

    public JLabel getDriveDoblajes() {
        return DriveDoblajes1;
    }

    public void setDriveDoblajes(JLabel DriveDoblajes) {
        this.DriveDoblajes1 = DriveDoblajes;
    }

    public JLabel getDriveEscensarios() {
        return DriveEscensarios1;
    }

    public void setDriveEscensarios(JLabel DriveEscensarios) {
        this.DriveEscensarios1 = DriveEscensarios;
    }

    public JLabel getDriveGuiones() {
        return DriveGuiones1;
    }

    public void setDriveGuiones(JLabel DriveGuiones) {
        this.DriveGuiones1 = DriveGuiones;
    }

    public JLabel getDriveGuiones6() {
        return DriveGuiones6;
    }

    public void setDriveGuiones6(JLabel DriveGuiones6) {
        this.DriveGuiones6 = DriveGuiones6;
    }

    public JLabel getDrivePlot() {
        return DrivePlot1;
    }

    public void setDrivePlot(JLabel DrivePlot) {
        this.DrivePlot1 = DrivePlot;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $faltasPM;
    private javax.swing.JLabel DirEstado1;
    private javax.swing.JLabel DriveAnimaciones1;
    private javax.swing.JLabel DriveDoblajes1;
    private javax.swing.JLabel DriveEscensarios1;
    private javax.swing.JLabel DriveGuiones1;
    private javax.swing.JLabel DriveGuiones6;
    private javax.swing.JLabel DrivePlot1;
    private javax.swing.JLabel EgresosNick1;
    private javax.swing.JLabel IngresosNick1;
    private javax.swing.JLabel PMestado1;
    private javax.swing.JLabel PMfaltas1;
    private javax.swing.JLabel UtilidadNick1;
    private javax.swing.JLabel capitulos1;
    private javax.swing.JLabel capitulosPT1;
    private javax.swing.JLabel deadline1;
    private javax.swing.JLabel diastrans1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
